windowManager: "bspwm"
userName: "Alice & Mélodie"
globalKeymap:
  keys:
    Mode:
      home: true
lunaraKeymap:
  keys:
    LeftTrigger:
      cmd: "Volume"
      args: ["--dec"]
    RightTrigger:
      cmd: "Volume"
      args: ["--inc"]
desktopKeymap:
  "2":
    leftStickMode: mouse
    rightStickMode: scroll
    keys:
      LeftTrigger:
        mouse: SU
      RightTrigger:
        mouse: SD
      North:
        keyboard:
          modifier: [ctrl]
          keys: ["t"]
      South:
        mouse: "L"
      East:
        mouse: "R"
