id: 01-volume
name: Volume
confirmation: false
icon: volume-2
queryVars:
  time: 1
  cmd: /bin/sh
  args:
    - -c
    - |
      v=$(amixer get Master | awk -F'[][]' 'END{print $2}' | tr -d '%'); printf '{"name":"Vol: %s%%","icon":"%s"}\n' "$v" "$( [ "$v" -gt 50 ] && echo volume-2 || echo volume )"
executor:
  - actionButton: B
    cmd: Volume
    args:
      - --inc
  - actionButton: X
    cmd: Volume
    args:
      - --dec
